spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
#    default-property-inclusion: non_null
#    serialization:
#      write-dates-as-timestamps: false
#    date-format: "yyyy-MM-dd HH:mm"
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: none
    #      ddl-auto: drop-and-create
    generate-ddl: true
  datasource:
    #url: "jdbc:h2:mem:test"
    url: "jdbc:h2:file:/data/sampledata"
    username: ""
    password: ""

    #url: "jdbc:h2:C:/data/sampledata"


  #url: "jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS TECH_SCHEMA\\;SET SCHEMA TECH_SCHEMA"
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    lt:
      techin: DEBUG
    org:
      springframework: INFO
#      springframework: DEBUG
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: DEBUG
      hibernate:
        SQL: DEBUG
        type: TRACE
      type:
        descriptor:
          sql:
            BasicBinder: INFO

application:
  version: 0.2
